E-BookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using E_Book_DataAccess.Data;
using E_Book_DataAccess.Repository.IRepository;
using E_Book_Model;
using Microsoft.AspNetCore.Mvc;

namespace E_BookWeb.Areas.Admin.Controllers
{
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _unit;
        public CoverTypeController(IUnitOfWork Db)
        {
            _unit = Db;
        }
        public IActionResult Index()
        {
            IEnumerable<Cover_type> cover_Types_List = _unit.CoverType.GetAll();
            return View(cover_Types_List);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Cover_type Cover_type)
        {
            //if (catogery.Name == catogery.DisplayOrder.ToString())
            //{
            //    ModelState.AddModelError("Name", "name and display can't match");
            //}
            if (ModelState.IsValid)
            {
                _unit.CoverType.Add(Cover_type);
                _unit.Save();
                TempData["success"] = "add data seccessfully";
                return RedirectToAction("Index");
            }
            return View(Cover_type);


        }
        [HttpGet]
        public IActionResult Edite(int? Id)
        {
            if (Id == null || Id == 0) return NotFound();
            var Cover_type = _unit.CoverType.GetFirstOrDefault(c => c.Id == Id);
            if (Cover_type == null) return NotFound();
            return View(Cover_type);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edite(Cover_type Cover_type)
        {
            //if (catogery.Name == catogery.DisplayOrder.ToString())
            //{
            //    ModelState.AddModelError("name", "name and display can't match");
            //}
            if (ModelState.IsValid)
            {
                _unit.CoverType.Update(Cover_type);
                _unit.Save();
                TempData["success"] = "update data seccessfully";
                return RedirectToAction("Index");
            }
            return View(Cover_type);


        }
        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0) return NotFound();
            var Cover_type = _unit.CoverType.GetFirstOrDefault(c => c.Id == Id);
            if (Cover_type == null) return NotFound();
            return View(Cover_type);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? Id)
        {

            var Cover_type = _unit.CoverType.GetFirstOrDefault(c => c.Id == Id);
            if (Cover_type == null) return NotFound();
            _unit.CoverType.Remove(Cover_type);
            _unit.Save();
            TempData["success"] = "delete data seccessfully";
            return RedirectToAction("Index");




        }
    }
}

E-BookWeb/Areas/Admin/Controllers/ProductController.cs
using E_Book_DataAccess.Data;
using E_Book_DataAccess.Repository.IRepository;
using E_Book_Model;
using E_Book_Model.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Cryptography.X509Certificates;

namespace E_BookWeb.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unit;
        private readonly IWebHostEnvironment _environment;
        public ProductController(IUnitOfWork Db, IWebHostEnvironment environment)
        {
            _unit = Db;
            _environment = environment;
        }
        public IActionResult Index()
        {
            //IEnumerable<Cover_type> cover_Types_List = _unit.CoverType.GetAll();
            return View();
        }


        [HttpGet]
        public IActionResult Upsert(int? Id)
        {
            ProductVM productVM = new()
            {
                product = new (),
                CatogeryList = _unit.Catogery.GetAll().Select(
                c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                }),
                CoverTypeList= _unit.CoverType.GetAll().Select(
                c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                })
            };

           
            if (Id == null || Id == 0)
            {
                ////create
                
                 
                return View(productVM);
            }
            else
            {
                productVM.product=_unit.Product.GetFirstOrDefault(p=>p.Id == Id);

            }
            return View(productVM);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM  obj,IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwrootpath = _environment.WebRootPath;
                if (file != null)
                {
                    string filename=Guid.NewGuid().ToString();
                    var uploads=Path.Combine(wwwrootpath,@"Images\Products");
                    var extention = Path.GetExtension(file.FileName);
                    if (obj.product.ImageUrl != null)
                    {
                        var oldimagepath = Path.Combine(wwwrootpath, obj.product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldimagepath))
                        {
                           
                            System.IO.File.Delete(oldimagepath);
                        }
                    }
                    using(var filestream=new FileStream(Path.Combine(uploads,filename+extention), FileMode.Create))
                    {
                        file.CopyTo(filestream);
                    }
                    obj.product.ImageUrl= @"Images\Products\"+filename+extention;

                }
                if (obj.product.Id == 0)
                {
                    _unit.Product.Add(obj.product);
                    _unit.Save();
                    TempData["success"] = "product  created seccessfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    _unit.Product.Update(obj.product);
                    _unit.Save();
                    TempData["success"] = "product  updated seccessfully";
                    return RedirectToAction("Index");
                }
            }
            return View(obj);


        }
       
        
        



        #region

        [HttpGet]
        public IActionResult GetAll()
        { string[] include =new string[] { "Catogery" , "Cover_Type" };
            var productlist = _unit.Product.GetAll(include);
            return Json(new {data =productlist});
        }

        [HttpDelete(Name = "Delete")]
        public IActionResult Delete(int? Id)
        {

            var product = _unit.Product.GetFirstOrDefault(c => c.Id == Id);
            if (product == null) return Json(new { success = false,message="error while deleting" }) ;
            var oldimagepath = Path.Combine(_environment.WebRootPath,  product.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldimagepath))
            {

                System.IO.File.Delete(oldimagepath);
            }
            _unit.Product.Remove(product);
            _unit.Save();
            //TempData["success"] = "delete data seccessfully";
            return Json(new { success = true, message = "delete successfull @ " });




        }


        #endregion
    }
}

E-BookWeb/Controllers/CatogeryController.cs
using E_Book_Model;
using E_BookWeb.Data;
 
using Microsoft.AspNetCore.Mvc;

namespace E_BookWeb.Controllers
{
    public class CatogeryController : Controller
    {
        private readonly AppDbContext _AppDbContext;
        public CatogeryController(AppDbContext appDbContext)
        {
            _AppDbContext = appDbContext;
        }
        public IActionResult Index()
        {
            IEnumerable<Catogery> CatogryList = _AppDbContext.Catogeries;
            return View(CatogryList);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Catogery catogery)
        {
            if (catogery.Name == catogery.DisplayOrder.ToString())
            {
                ModelState.AddModelError("ss", "name and display can't match");
            }
            if (ModelState.IsValid)
            {
                _AppDbContext.Catogeries.Add(catogery);
                _AppDbContext.SaveChanges();
                TempData["success"] = "add data seccessfully";
                return RedirectToAction("Index");
            }
            return View(catogery);


        }
        [HttpGet]
        public IActionResult Edite(int? Id)
        {
            if (Id == null || Id == 0) return NotFound();
            var catogery= _AppDbContext.Catogeries.Find(Id);
            if(catogery == null) return NotFound();
            return View(catogery);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edite(Catogery catogery )
        {
            if (catogery.Name == catogery.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "name and display can't match");
            }
            if (ModelState.IsValid)
            {
                _AppDbContext.Catogeries.Update(catogery);
                _AppDbContext.SaveChanges();
                TempData["success"] = "update data seccessfully";
                return RedirectToAction("Index");
            }
            return View(catogery);


        }
        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0) return NotFound();
            var catogery = _AppDbContext.Catogeries.Find(Id);
            if (catogery == null) return NotFound();
            return View(catogery);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? Id)
        {

            var catogery = _AppDbContext.Catogeries.Find(Id);
            if(catogery == null) return NotFound();
            _AppDbContext.Catogeries.Remove(catogery);
                _AppDbContext.SaveChanges();
            TempData["success"] = "delete data seccessfully";
                return RedirectToAction("Index");
            
           


        }
    }
}

E-BookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E_BookWeb</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/BootswatchTheme.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/E_BookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/2.1.6/css/dataTables.dataTables.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid" bis_skin_checked="1">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E_BookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02" bis_skin_checked="1">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link  " asp-area="Customer" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                           
                        </li>
                        <li class="nav-item">
                            
                        </li>
                         
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Managment</a>
                            <div class="dropdown-menu" bis_skin_checked="1">
                                <a class="dropdown-item  " asp-area="Admin"   asp-controller="Catogery" asp-action="Index">Catogery</a>
                                <a class="dropdown-item  " asp-area="Admin"   asp-controller="CoverType" asp-action="Index">Cover Type</a>
                                <a class="dropdown-item  " asp-area="Admin"   asp-controller="Product" asp-action="Index">Product</a>
                                 
                                <div class="dropdown-divider" bis_skin_checked="1"></div>
                               
                            </div>
                        </li>
                    </ul>
                    @*<form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>*@
                </div>
            </div>
        </nav>
        @*kkk*@
         
    </header>
    <div class="container" >
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer style="position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
height: 50px;
  
   
  color: white;
  text-align: left;" class="  footer text-muted bg-primary">
     
        <div class="container">
            &copy; 2024 - E_BookWeb - @*<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/2.1.6/js/dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    
    <script src="https://cdn.tiny.cloud/1/f646xq8seon12ph4w3inyc8vkqfs0lxz3tuvemkx73ru5gxf/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>

     

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

E-BookWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">toastr.success(' @TempData["success"]')</script>
}
@if (TempData["error"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">toastr.error(' @TempData["error"]')</script>
}