E-BookWeb/Areas/Admin/Controllers/CatogeryController.cs
using E_Book_DataAccess.Data;
using E_Book_DataAccess.Repository.IRepository;
using E_Book_Model;
using Microsoft.AspNetCore.Mvc;

namespace E_BookWeb.Areas.Admin.Controllers
{
    public class CatogeryController : Controller
    {
        private readonly IUnitOfWork _unit;
        public CatogeryController(IUnitOfWork Db)
        {
            _unit = Db;
        }
        public IActionResult Index()
        {
            IEnumerable<Catogery> CatogryList = _unit.Catogery.GetAll();
            return View(CatogryList);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Catogery catogery)
        {
            if (catogery.Name == catogery.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "name and display can't match");
            }
            if (ModelState.IsValid)
            {
                _unit.Catogery.Add(catogery);
                _unit.Save();
                TempData["success"] = "add data seccessfully";
                return RedirectToAction("Index");
            }
            return View(catogery);


        }
        [HttpGet]
        public IActionResult Edite(int? Id)
        {
            if (Id == null || Id == 0) return NotFound();
            var catogery = _unit.Catogery.GetFirstOrDefault(c => c.Id == Id);
            if (catogery == null) return NotFound();
            return View(catogery);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edite(Catogery catogery)
        {
            if (catogery.Name == catogery.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "name and display can't match");
            }
            if (ModelState.IsValid)
            {
                _unit.Catogery.Update(catogery);
                _unit.Save();
                TempData["success"] = "update data seccessfully";
                return RedirectToAction("Index");
            }
            return View(catogery);


        }
        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0) return NotFound();
            var catogery = _unit.Catogery.GetFirstOrDefault(c => c.Id == Id);
            if (catogery == null) return NotFound();
            return View(catogery);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? Id)
        {

            var catogery = _unit.Catogery.GetFirstOrDefault(c => c.Id == Id);
            if (catogery == null) return NotFound();
            _unit.Catogery.Remove(catogery);
            _unit.Save();
            TempData["success"] = "delete data seccessfully";
            return RedirectToAction("Index");




        }
    }
}

E-BookWeb/Controllers/CatogeryController.cs
using E_Book_Model;
using E_BookWeb.Data;
 
using Microsoft.AspNetCore.Mvc;

namespace E_BookWeb.Controllers
{
    public class CatogeryController : Controller
    {
        private readonly AppDbContext _AppDbContext;
        public CatogeryController(AppDbContext appDbContext)
        {
            _AppDbContext = appDbContext;
        }
        public IActionResult Index()
        {
            IEnumerable<Catogery> CatogryList = _AppDbContext.Catogeries;
            return View(CatogryList);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Catogery catogery)
        {
            if (catogery.Name == catogery.DisplayOrder.ToString())
            {
                ModelState.AddModelError("ss", "name and display can't match");
            }
            if (ModelState.IsValid)
            {
                _AppDbContext.Catogeries.Add(catogery);
                _AppDbContext.SaveChanges();
                TempData["success"] = "add data seccessfully";
                return RedirectToAction("Index");
            }
            return View(catogery);


        }
        [HttpGet]
        public IActionResult Edite(int? Id)
        {
            if (Id == null || Id == 0) return NotFound();
            var catogery= _AppDbContext.Catogeries.Find(Id);
            if(catogery == null) return NotFound();
            return View(catogery);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edite(Catogery catogery )
        {
            if (catogery.Name == catogery.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "name and display can't match");
            }
            if (ModelState.IsValid)
            {
                _AppDbContext.Catogeries.Update(catogery);
                _AppDbContext.SaveChanges();
                TempData["success"] = "update data seccessfully";
                return RedirectToAction("Index");
            }
            return View(catogery);


        }
        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0) return NotFound();
            var catogery = _AppDbContext.Catogeries.Find(Id);
            if (catogery == null) return NotFound();
            return View(catogery);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? Id)
        {

            var catogery = _AppDbContext.Catogeries.Find(Id);
            if(catogery == null) return NotFound();
            _AppDbContext.Catogeries.Remove(catogery);
                _AppDbContext.SaveChanges();
            TempData["success"] = "delete data seccessfully";
                return RedirectToAction("Index");
            
           


        }
    }
}

E-BookWeb/Areas/Admin/Views/Catogery/Create.cshtml
@model E_Book_Model.Catogery
<form method="post">
	<div class=" border p-3 mb-4">
		<div class="row pb-2">

			<h2 class="text-primary"> Create Catogery</h2>
			<hr />
		@*</div><div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="DisplayOrder"></label>
			<input asp-for="DisplayOrder" class="form-control" />
			<span asp-validation-for="DisplayOrder" class="text-danger"></span>
			</div><div class="mb-3">
		<button class="btn btn-primary" style="width:150px">Create</button>
		<a asp-action="Index" asp-controller="Catogery" class="btn btn-secondary" style="width:150px">Back to LIst</a>
			</div>
		</div>
</form>
@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
	}

E-BookWeb/Areas/Admin/Views/Catogery/Delete.cshtml
@model E_Book_Model.Catogery
<form method="post" asp-action="DeletePost">
	<input asp-for="Id" hidden />
	<div class=" border p-3 mb-4">
		<div class="row pb-2">
			
			<h2 class="text-primary"> Delete Catogery</h2>
			<hr />
		@*</div><div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
				<input asp-for="Name" class="form-control" disabled />
			@*<span asp-validation-for="Name" class="text-danger"></span>*@
		</div>
		<div class="mb-3">
			<label asp-for="DisplayOrder"></label>
				<input asp-for="DisplayOrder" class="form-control" disabled />
			@*<span asp-validation-for="DisplayOrder" class="text-danger"></span>*@
		</div>
			<button class="btn btn-danger" style="width:150px" type="submit" >Delete</button>
		<a asp-action="Index" asp-controller="Catogery" class="btn btn-secondary" style="width:150px">Back to LIst</a>
	</div>
</form>
@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
	}

E-BookWeb/Areas/Admin/Views/Catogery/Edite.cshtml
@model E_Book_Model.Catogery
<form method="post" >
	<div class=" border p-3 mb-4">
		<div class="row pb-2">

			<h2 class="text-primary"> Edite Catogery</h2>
			<hr />
		@*</div><div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="DisplayOrder"></label>
			<input asp-for="DisplayOrder" class="form-control" />
			<span asp-validation-for="DisplayOrder" class="text-danger"></span>
		</div>
			<button class="btn btn-primary" style="width:150px" type="submit">Edite</button>
		<a asp-action="Index" asp-controller="Catogery" class="btn btn-secondary" style="width:150px">Back to LIst</a>
	</div>
</form>
@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
	}

E-BookWeb/Areas/Admin/Views/Catogery/Index.cshtml
@model IEnumerable<E_Book_Model.Catogery>
@{
	ViewData["Title"] = "Index";
}


<div class="container p-2">
	<div class="row pt-4">
		<div class="col-6"><h2 class="text-primary">   Catogery List</h2></div>
		<div class="col-6 text-end">
			<a asp-action="Create" asp-controller="Catogery" class="btn btn-primary">
				<i class="bi bi-plus-circle"></i>&nbsp   Create New Catogery
			</a>
		</div>
	</div>

	<br />
	<table class="table table-bordered table-striped   " style="width:100%">
		<thead>
			<tr>
				<th scope="col">ID</th>
				<th scope="col">Name</th>
				<th scope="col">DisplayOrder</th>
				<th scope="col">CreatedDateTime</th>
				<th scope="col">Edite</th>
				<th scope="col">Delete</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var obj in Model)
			{
				<tr>
					<th scope="row">@obj.Id</th>
					<td>@obj.Name</td>
					<td>@obj.DisplayOrder</td>
					<td>@obj.CreatedDateTime</td>
					<td><div class="w-75 bnt-group" role="group">
						<a asp-action="Edite" asp-controller="Catogery" asp-route-Id=@obj.Id class="btn btn-primary mx-2">
							<i class="bi bi-pencil-square"></i> Edit</a>
						</div>
					</td>
					<td>
						<div class="w-75 bnt-group" role="group">
							<a asp-action="Delete" asp-controller="Catogery" asp-route-Id=@obj.Id class="btn btn-danger mx-2">
								<i class="bi bi-trash3"></i> Delete
							</a>
						</div>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>